AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template for Global resources

Resources:
  # Lambdas
  PublishToSnsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./backend/functions/global
      Handler: publishToSns.handler
      Runtime: nodejs14.x
      Events:
        apiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /publishsns
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt JacktripSnsTopic.TopicName

      Environment:
        Variables:
          snsTopicArn: !Ref JacktripSnsTopic

  # SNS
  JacktripSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: JacktripSnsTopic
      FifoTopic: true
      ContentBasedDeduplication: true
      TopicName: JacktripSnsTopic.fifo

  # IAM Roles
  JacktripStateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: JacktripStateMachineRole
      Description: Role used by the Step Functions State Machine
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: JacktripStateMachineInvokeLambda
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - Fn::Sub: arn:*:lambda:*:${AWS::AccountId}:function:jacktrip*
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess

Outputs:
  StateMachineRoleArn:
    Description: Arn for the Jacktrip State Machine
    Value: !GetAtt JacktripStateMachineRole.Arn
  SnsTopicArn:
    Description: Arn for the Jacktrip State Machine
    Value: !Ref JacktripSnsTopic
