Transform: AWS::Serverless-2016-10-31
Description: 'CloudFormation Template for instantiating Jacktrip servers in AWS'

Parameters:
  JacktripEventSource:
    Description: 'Event source name for the web portal'
    Type: String
    Default: 'web_portal'

  JacktripEventDetailType:
    Description: 'Detail type for Jacktrip events'
    Type: String
    Default: 'Jacktrip Server Event Notification'

Resources:
  # Lambdas
  CreateServerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./backend
      Runtime: nodejs14.x
      Handler: functions/createServer.handler

  TerminateServerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./backend
      Runtime: nodejs14.x
      Handler: functions/terminateServer.handler

  # DynamoDB
  ServerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: user
          AttributeType: S
        - AttributeName: server_name
          AttributeType: S
      KeySchema:
        - AttributeName: user
          KeyType: HASH
        - AttributeName: server_name
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  # EventBridge
  JacktripBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub 'JacktripEventBus-${AWS::Region}'

  JacktripBusPolicy:
    Type: AWS::Events::EventBusPolicy
    Properties:
      StatementId: !Sub '${JacktripBus}-Policy'
      Action: events:PutEvents
      Principal: !Ref AWS::AccountId
      EventBusName: !Ref JacktripBus

  JacktripServerRule:
    Type: AWS::Events::Rule
    Properties:
      Description: 'Rule matching Jacktrip events'
      EventPattern:
        source:
          - !Ref JacktripEventSource
        detail-type:
          - !Ref JacktripEventDetailType
      EventBusName: !Ref JacktripBus
      Targets:
        - Arn: !Ref JacktripStateMachine
          Id: 'JacktripStateMachine'
          InputPath: $.detail
          RoleArn: !Ref EventRuleStateMachineRole

  # Step Functions
  JacktripStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: ./backend/state_machine/state_machine.asl.json
      DefinitionSubstitutions:
        CreateServerFunctionArn: !GetAtt CreateServerFunction.Arn
        TerminateServerFunctionArn: !GetAtt TerminateServerFunction.Arn
      Logging:
        Level: ALL
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt StateMachineLogGroup.Arn
      Role: !Ref JacktripStateMachineRole

  StateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '${AWS::StackName}-StateMachine-LogGroup'

  # IAM Roles
  JacktripStateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      Description: 'Role used by the Step Functions State Machine'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: Jacktrip_State_Machine_Role
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !GetAtt CreateServerFunction.Arn
                  - !GetAtt TerminateServerFunction.Arn
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess

  EventRuleStateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      Description: 'Role used by Event Rule to invoke Step Functions'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InvokeJacktripStepFunctions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource: !Ref JacktripStateMachine
