Transform: AWS::Serverless-2016-10-31
Description: 'CloudFormation Template for instantiating Jacktrip servers in AWS'

Parameters:
  JacktripEventSource:
    Description: 'Event source name for the web portal'
    Type: String
    Default: 'web_portal'

  JacktripEventDetailType:
    Description: 'Detail type for Jacktrip events'
    Type: String
    Default: 'Jacktrip Server Event Notification'

Resources:
  # Lambdas
  JacktripCreateServer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./backend
      Runtime: nodejs14.x
      Handler: functions/createServer.handler

  JacktripTerminateServer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./backend
      Runtime: nodejs14.x
      Handler: functions/terminateServer.handler

  # EventBridge
  JacktripBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub 'JacktripEventBus-${AWS::Region}'

  JacktripBusPolicy:
    Type: AWS::Events::EventBusPolicy
    Properties:
      StatementId: !Sub '${JacktripBus}-Policy'
      Action: events:PutEvents
      Principal: !Ref AWS::AccountId
      EventBusName: !Ref JacktripBus

  # CentralEventRule:
  #   Condition: IsCentral
  #   Type: AWS::Events::Rule
  #   Properties:
  #     Description: "Rule in central region sending events to other regions"
  #     EventPattern:
  RegionalEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: 'Rule in each region matching Jacktrip events'
      EventPattern:
        source:
          - !Ref JacktripEventSource
        detail-type:
          - !Ref JacktripEventDetailType
        detail:
          region:
            - !Ref AWS::Region
      EventBusName: !Ref JacktripBus
      Targets:
        - Arn: !Ref JacktripStateMachine
          Id: 'JacktripStateMachine'
          InputPath: $.detail
          RoleArn: '{{resolve:ssm:JacktripEventRuleRole}}'

  # Step Functions
  JacktripStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: ./backend/state_machine/state_machine.asl.json
      DefinitionSubstitutions:
        CreateServerFunctionArn: !GetAtt JacktripCreateServer.Arn
        TerminateServerFunctionArn: !GetAtt JacktripTerminateServer.Arn
      Logging:
        Level: ALL
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt StateMachineLogGroup.Arn
      Role: '{{resolve:ssm:JacktripStateMachineRole}}'

  StateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub 'Jacktrip-StateMachine-LogGroup-${AWS::Region}'
